apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service-loadbalancer
  labels:
    name: nodejs-app-loadbalancer
    app: nodejs-app
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
