apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  labels:
    name: nodejs-app-nodeport
    app: nodejs-app
spec:
  type: NodePort
  selector:
    name: nodejs-app
    app: nodejs-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
