apiVersion: v1
kind: Pod
metadata:
  name: nodejs-app
  labels:
    name: nodejs-app
    app: nodejs-app
spec:
  containers:
    - name: nodejs-app
      image: isuruherath22923/docker-example
      ports:
        - containerPort: 80
